import '../models/product_model.dart';
import '../models/store_model.dart';

class MockData {
  static List<StoreModel> get stores => [
        StoreModel(
          id: 'store_1',
          ownerId: 'vendor_1',
          name: 'Krishna Kirana Store',
          description: 'Your trusted neighbourhood grocery store since 1995. Fresh products daily.',
          category: 'Grocery & Kirana',
          phone: '9876543210',
          address: '42, MG Road, Koramangala',
          city: 'Bangalore',
          pincode: '560034',
          latitude: 12.9352,
          longitude: 77.6245,
          imageUrl: 'https://picsum.photos/seed/store1/400/400',
          bannerUrl: 'https://picsum.photos/seed/banner1/800/400',
          rating: 4.5,
          totalRatings: 234,
          isOpen: true,
          openTime: '07:00',
          closeTime: '22:00',
          offersDelivery: true,
          deliveryRadius: 3.0,
          minOrderAmount: 99,
          deliveryFee: 20,
          upiId: 'saroja.vvce@oksbi',
          isVerified: true,
          createdAt: DateTime(2024, 1, 15),
        ),
        StoreModel(
          id: 'store_2',
          ownerId: 'vendor_2',
          name: 'Fresh Farm Veggies',
          description: 'Farm-fresh vegetables and fruits delivered from local farms every morning.',
          category: 'Fruits & Vegetables',
          phone: '9876543211',
          address: '15, 4th Cross, Indiranagar',
          city: 'Bangalore',
          pincode: '560038',
          latitude: 12.9784,
          longitude: 77.6408,
          imageUrl: 'https://picsum.photos/seed/store2/400/400',
          bannerUrl: 'https://picsum.photos/seed/banner2/800/400',
          rating: 4.7,
          totalRatings: 189,
          isOpen: true,
          openTime: '06:00',
          closeTime: '20:00',
          offersDelivery: true,
          deliveryRadius: 4.0,
          minOrderAmount: 149,
          deliveryFee: 25,
          upiId: 'freshfarm@upi',
          isVerified: true,
          createdAt: DateTime(2024, 3, 1),
        ),
        StoreModel(
          id: 'store_3',
          ownerId: 'vendor_3',
          name: 'Annapurna Sweets & Bakery',
          description: 'Traditional Indian sweets, fresh bakery items, and custom cakes.',
          category: 'Bakery & Sweets',
          phone: '9876543212',
          address: '88, Church Street, MG Road',
          city: 'Bangalore',
          pincode: '560001',
          latitude: 12.9756,
          longitude: 77.6068,
          imageUrl: 'https://picsum.photos/seed/store3/400/400',
          bannerUrl: 'https://picsum.photos/seed/banner3/800/400',
          rating: 4.8,
          totalRatings: 567,
          isOpen: true,
          openTime: '08:00',
          closeTime: '21:30',
          offersDelivery: true,
          deliveryRadius: 5.0,
          minOrderAmount: 199,
          deliveryFee: 30,
          upiId: 'annapurna@upi',
          isVerified: true,
          createdAt: DateTime(2023, 11, 20),
        ),
        StoreModel(
          id: 'store_4',
          ownerId: 'vendor_4',
          name: 'MedPlus Pharmacy',
          description: 'All medicines, health supplements, and personal care products.',
          category: 'Pharmacy',
          phone: '9876543213',
          address: '3, 1st Main, HSR Layout',
          city: 'Bangalore',
          pincode: '560102',
          latitude: 12.9116,
          longitude: 77.6474,
          imageUrl: 'https://picsum.photos/seed/store4/400/400',
          bannerUrl: 'https://picsum.photos/seed/banner4/800/400',
          rating: 4.3,
          totalRatings: 145,
          isOpen: true,
          openTime: '08:00',
          closeTime: '23:00',
          offersDelivery: true,
          deliveryRadius: 3.5,
          minOrderAmount: 0,
          deliveryFee: 15,
          upiId: 'medplus@upi',
          isVerified: true,
          createdAt: DateTime(2024, 2, 10),
        ),
        StoreModel(
          id: 'store_5',
          ownerId: 'vendor_5',
          name: 'Amma Dairy Fresh',
          description: 'Pure milk, curd, paneer, ghee, and dairy products delivered fresh.',
          category: 'Dairy & Milk',
          phone: '9876543214',
          address: '22, 5th Block, Jayanagar',
          city: 'Bangalore',
          pincode: '560041',
          latitude: 12.9254,
          longitude: 77.5838,
          imageUrl: 'https://picsum.photos/seed/store5/400/400',
          bannerUrl: 'https://picsum.photos/seed/banner5/800/400',
          rating: 4.6,
          totalRatings: 312,
          isOpen: true,
          openTime: '05:30',
          closeTime: '19:00',
          offersDelivery: true,
          deliveryRadius: 4.0,
          minOrderAmount: 50,
          deliveryFee: 10,
          upiId: 'ammadairy@upi',
          isVerified: true,
          createdAt: DateTime(2024, 1, 5),
        ),
      ];

  static List<ProductModel> getProductsForStore(String storeId) {
    switch (storeId) {
      case 'store_1':
        return _kiranaProducts;
      case 'store_2':
        return _veggieProducts;
      case 'store_3':
        return _bakeryProducts;
      case 'store_4':
        return _pharmacyProducts;
      case 'store_5':
        return _dairyProducts;
      default:
        return _kiranaProducts;
    }
  }

  static List<ProductModel> get allProducts {
    return [
      ..._kiranaProducts,
      ..._veggieProducts,
      ..._bakeryProducts,
      ..._pharmacyProducts,
      ..._dairyProducts,
    ];
  }

  static final List<ProductModel> _kiranaProducts = [
    ProductModel(
      id: 'p1',
      storeId: 'store_1',
      name: 'Tata Gold Tea',
      description: 'Premium blend tea, 500g pack',
      category: 'Beverages',
      price: 245,
      mrp: 280,
      unit: 'pack',
      imageUrl: 'https://picsum.photos/seed/tea/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p2',
      storeId: 'store_1',
      name: 'Aashirvaad Atta',
      description: 'Whole wheat flour, 5kg bag',
      category: 'Staples',
      price: 265,
      mrp: 310,
      unit: 'kg',
      quantity: 5,
      imageUrl: 'https://picsum.photos/seed/atta/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p3',
      storeId: 'store_1',
      name: 'Fortune Sunflower Oil',
      description: 'Refined sunflower oil, 1L',
      category: 'Cooking Oil',
      price: 145,
      mrp: 165,
      unit: 'L',
      imageUrl: 'https://picsum.photos/seed/oil/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p4',
      storeId: 'store_1',
      name: 'Maggi Noodles (Pack of 12)',
      description: 'Masala instant noodles',
      category: 'Snacks',
      price: 168,
      mrp: 180,
      unit: 'pack',
      imageUrl: 'https://picsum.photos/seed/maggi/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p5',
      storeId: 'store_1',
      name: 'Toor Dal',
      description: 'Premium unpolished toor dal, 1kg',
      category: 'Pulses',
      price: 155,
      mrp: 180,
      unit: 'kg',
      imageUrl: 'https://picsum.photos/seed/dal/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
  ];

  static final List<ProductModel> _veggieProducts = [
    ProductModel(
      id: 'p6',
      storeId: 'store_2',
      name: 'Fresh Tomatoes',
      description: 'Locally grown, handpicked tomatoes',
      category: 'Vegetables',
      price: 40,
      mrp: 50,
      unit: 'kg',
      imageUrl: 'https://picsum.photos/seed/tomato/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p7',
      storeId: 'store_2',
      name: 'Onions',
      description: 'Fresh red onions',
      category: 'Vegetables',
      price: 35,
      mrp: 45,
      unit: 'kg',
      imageUrl: 'https://picsum.photos/seed/onion/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p8',
      storeId: 'store_2',
      name: 'Banana (Elakki)',
      description: 'Sweet baby bananas, 1 dozen',
      category: 'Fruits',
      price: 60,
      mrp: 70,
      unit: 'dozen',
      imageUrl: 'https://picsum.photos/seed/banana/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p9',
      storeId: 'store_2',
      name: 'Spinach (Palak)',
      description: 'Fresh organic spinach bunch',
      category: 'Leafy Greens',
      price: 25,
      unit: 'piece',
      imageUrl: 'https://picsum.photos/seed/spinach/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
  ];

  static final List<ProductModel> _bakeryProducts = [
    ProductModel(
      id: 'p10',
      storeId: 'store_3',
      name: 'Mysore Pak',
      description: 'Traditional ghee mysore pak, 250g',
      category: 'Sweets',
      price: 180,
      unit: 'pack',
      imageUrl: 'https://picsum.photos/seed/mysorepak/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p11',
      storeId: 'store_3',
      name: 'Butter Croissant',
      description: 'Freshly baked French croissant',
      category: 'Bakery',
      price: 65,
      mrp: 75,
      unit: 'piece',
      imageUrl: 'https://picsum.photos/seed/croissant/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p12',
      storeId: 'store_3',
      name: 'Gulab Jamun (12 pcs)',
      description: 'Soft, melt-in-mouth gulab jamuns',
      category: 'Sweets',
      price: 220,
      unit: 'box',
      imageUrl: 'https://picsum.photos/seed/gulabjamun/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
  ];

  static final List<ProductModel> _pharmacyProducts = [
    ProductModel(
      id: 'p13',
      storeId: 'store_4',
      name: 'Dolo 650mg',
      description: 'Paracetamol tablets, strip of 15',
      category: 'Medicines',
      price: 32,
      mrp: 35,
      unit: 'pack',
      imageUrl: 'https://picsum.photos/seed/medicine1/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p14',
      storeId: 'store_4',
      name: 'ORS Electral Powder',
      description: 'Oral rehydration salts, pack of 10',
      category: 'Health',
      price: 65,
      mrp: 72,
      unit: 'pack',
      imageUrl: 'https://picsum.photos/seed/medicine2/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
  ];

  static final List<ProductModel> _dairyProducts = [
    ProductModel(
      id: 'p15',
      storeId: 'store_5',
      name: 'Fresh Cow Milk',
      description: 'Pure pasteurized cow milk, 500ml',
      category: 'Milk',
      price: 28,
      mrp: 30,
      unit: 'ml',
      quantity: 500,
      imageUrl: 'https://picsum.photos/seed/milk/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p16',
      storeId: 'store_5',
      name: 'Homemade Paneer',
      description: 'Fresh cottage cheese, 200g',
      category: 'Dairy',
      price: 80,
      mrp: 95,
      unit: 'g',
      quantity: 200,
      imageUrl: 'https://picsum.photos/seed/paneer/300/300',
      isFeatured: true,
      createdAt: DateTime(2024, 5, 1),
    ),
    ProductModel(
      id: 'p17',
      storeId: 'store_5',
      name: 'Curd (Dahi)',
      description: 'Thick set curd, 400g',
      category: 'Dairy',
      price: 35,
      mrp: 40,
      unit: 'g',
      quantity: 400,
      imageUrl: 'https://picsum.photos/seed/curd/300/300',
      createdAt: DateTime(2024, 5, 1),
    ),
  ];
}
